#!/usr/local/bin/tcl
# File generated by xotclIDE
# edit if you want


set sname [info script]
if {$sname==""} {
    # Run interactive for develop purposes
    set progdir [pwd]
} else {
    file lstat $sname stats
    # follow sym links
    if {$stats(type)=="link"} {
        set sname [file readlink $sname]
        if {[file pathtype $sname]=="relative"} {
            set sname [file join [file dirname [info script]] $sname]
        }
    }
    set progdir [file dirname $sname]
}

lappend auto_path [file dirname $progdir]

# Lade Weitere Tcl Komponenten Xotc,tDom,TclX
source [file join $progdir Init.tcl]
package require xdobry::sql
package require xdobry::Validate
package require xdobry::ValidateGUI
package require xdobry::FormEngine
package require xdobry::FormFactory
package require xdobry::DBProxy
package require xdobry::FE_Services
package require xdobry::FormServer
# default Optionen für FormServer Setzen

#Die FormEngine müssen zuerst zerstör werden weil sie 
#beim delete noch die SQL-Connect brauchen
set globalexit 0
Object setExitHandler {
    global globalexit
    set globalexit 1
}
if {!$tcl_interactive && [llength $argv]>=1} {
    if {[llength $argv]==1 && $argv!="-help" && ![string match -* $argv]} {
	set FormServer::opts(xmlfile) $argv
    } else {
	package require opt
	set pkey [::tcl::OptProc ::tcl::OptParseFS {
	    {-connect -string {} "db connect parameters f.e. {interface mysql} {dbname dbank} {user root}"}
	    {-noconnectdialog "connect to database without connect dialog"}
	    {-viewonly "use forms only for viewing data"}
	    {-ignorexmlpar "not use xml coded connect parameters"}
	    {-loadmacros -string {} "load macros script"}
	    {-debug "Anable debug functions"}
	    {-openform -string {} "open form by starting application"}
	    {?xmlfile? -string {} "XML formular description file .xmlforms"}
	} {
            foreach v [info locals] {
		set FormServer::opts($v) [set $v]
	    } } ]
	eval ::tcl::OptParseFS $argv
	::tcl::OptKeyDelete $pkey
    }
}

FormServerWin startSystem
