# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded IDEBaseGUI 0.81 [list source [file join $dir IDEBaseGUI.xotcl]]
package ifneeded IDEErrorReporter 0.74 [list source [file join $dir IDEErrorReporter.xotcl]]
package ifneeded KeyedList 0.2 [list source [file join $dir KeyedList.xotcl]]
package ifneeded base64 2.2.2 [list source [file join $dir base64.xotcl]]
package ifneeded xdobry::AssAssistent 0.33 [list source [file join $dir xdobry_AssAssistent.xotcl]]
package ifneeded xdobry::Base 0.34 [list source [file join $dir xdobry_Base.xotcl]]
package ifneeded xdobry::Container 0.22 [list source [file join $dir xdobry_Container.xotcl]]
package ifneeded xdobry::DBProxy 0.31 [list source [file join $dir xdobry_DBProxy.xotcl]]
package ifneeded xdobry::Dialog 0.32 [list source [file join $dir xdobry_Dialog.xotcl]]
package ifneeded xdobry::EditableWidget 0.31 [list source [file join $dir xdobry_EditableWidget.xotcl]]
package ifneeded xdobry::FE_Services 0.32 [list source [file join $dir xdobry_FE_Services.xotcl]]
package ifneeded xdobry::FormEditor 0.33 [list source [file join $dir xdobry_FormEditor.xotcl]]
package ifneeded xdobry::FormEngine 0.33 [list source [file join $dir xdobry_FormEngine.xotcl]]
package ifneeded xdobry::FormFactory 0.32 [list source [file join $dir xdobry_FormFactory.xotcl]]
package ifneeded xdobry::FormGenerator 0.31 [list source [file join $dir xdobry_FormGenerator.xotcl]]
package ifneeded xdobry::FormServer 0.33 [list source [file join $dir xdobry_FormServer.xotcl]]
package ifneeded xdobry::GUIEditor 0.32 [list source [file join $dir xdobry_GUIEditor.xotcl]]
package ifneeded xdobry::ReverseEngeneering 0.31 [list source [file join $dir xdobry_ReverseEngeneering.xotcl]]
package ifneeded xdobry::SchemaEditGUI 0.32 [list source [file join $dir xdobry_SchemaEditGUI.xotcl]]
package ifneeded xdobry::SchemaEditor 0.33 [list source [file join $dir xdobry_SchemaEditor.xotcl]]
package ifneeded xdobry::Validate 0.22 [list source [file join $dir xdobry_Validate.xotcl]]
package ifneeded xdobry::ValidateGUI 0.23 [list source [file join $dir xdobry_ValidateGUI.xotcl]]
package ifneeded xdobry::WidgetLib 0.33 [list source [file join $dir xdobry_WidgetLib.xotcl]]
package ifneeded xdobry::access 0.73 [list source [file join $dir xdobry_access.xotcl]]
package ifneeded xdobry::mssql 0.61 [list source [file join $dir xdobry_mssql.xotcl]]
package ifneeded xdobry::mysql 0.75 [list source [file join $dir xdobry_mysql.xotcl]]
package ifneeded xdobry::odbc 0.74 [list source [file join $dir xdobry_odbc.xotcl]]
package ifneeded xdobry::oratcl 0.74 [list source [file join $dir xdobry_oratcl.xotcl]]
package ifneeded xdobry::pgsql 0.74 [list source [file join $dir xdobry_pgsql.xotcl]]
package ifneeded xdobry::scripts 0.1 [list source [file join $dir xdobry_scripts.xotcl]]
package ifneeded xdobry::sql 0.78 [list source [file join $dir xdobry_sql.xotcl]]
package ifneeded xdobry::sqlDebug 0.35 [list source [file join $dir xdobry_sqlDebug.xotcl]]
package ifneeded xdobry::sqlite 0.76 [list source [file join $dir xdobry_sqlite.xotcl]]
