#!/usr/local/bin/tcl
# File generated by xotclIDE
# edit if you want

set sname [info script]
if {$sname==""} {
    # Run interactive for develop purposes
    set progdir [pwd]
} else {
    file lstat $sname stats
    # follow sym links
    if {$stats(type)=="link"} {
        set sname [file readlink $sname]
        if {[file pathtype $sname]=="relative"} {
            set sname [file join [file dirname [info script]] $sname]
        }
    }
    set progdir [file dirname $sname]
}

lappend auto_path [file dirname $progdir]


# Lade Weitere Tcl Komponenten Xotc,tDom,TclX
source [file join $progdir Init.tcl]
package require xdobry::sql
package require xdobry::SchemaEditGUI
package require xdobry::ValidateGUI
package require xdobry::AssAssistent
package require xdobry::ReverseEngeneering
package require xdobry::SchemaEditor

SchemaEditorWin startSystem

